services:
  nginx:
    image: nginx:latest
    container_name: eexam_nginx
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - eexam-network
    depends_on:
      - web
      - api

  web:
    image: nguyenhuutan080603044/e-exam-frontend:latest
    container_name: eexam_web
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=/api
    command: npm run start
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - eexam-network

  api:
    image: nguyenhuutan080603044/e-exam-backend:prisma
    container_name: eexam_api
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3003
      DATABASE_URL: 'postgresql://postgres:postgres@db:5432/eexam'
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eexam
      POSTGRES_PORT: 5432
    command: sh -c "bunx prisma migrate deploy && bun dist/src/main.js"
    restart: unless-stopped
    networks:
      - eexam-network

  db:
    image: postgres:17
    container_name: eexam_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=eexam
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - eexam-network

volumes:
  pgdata:
    driver: local

networks:
  eexam-network:
    driver: bridge
